version: '2'
services:
  
  db:
    container_name: basb_db
    image: postgres:10
    ports:
      - "5070:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata 
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata  
    restart: always

  web:
    container_name: basb_web
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "12000:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - web-data:/var/lib/odoo
    restart: always

volumes:
  db-data:
  web-data:
