from . import res_users
from . import pos_order
from . import order_note
from . import product_template
from . import res_partner
from . import stock_quant
from . import pos_order_report_inherited
from . import pos_config_inherited
from . import pos_config